name: Docker Image CI

on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  docker_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        trex_version:
          - "0.20.3"
          - "0.20.1"
          - "0.20.0"
        cuda_version:
          - "11.3.0"
          - "11.2.1"
          - "11.2.0"
          - "11.1"
          - "11.0"
          - "10.2"
    steps:
      - name: Checko Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/miner-trex-cuda:v${{matrix.trex_version}}_cuda${{ matrix.cuda_version }}
          build-args: |
            TREX_VERSION=${{ matrix.trex_version }}
            NVIDIA_CUDA_VERSION=${{ matrix.cuda_version }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


  docker_description:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: peterevans/dockerhub-description
