name: Docker Image CI

on:
  push:
    branches:
      - master
    # paths:
    #   - "/VERSION"

jobs:
  get-matrix:
    runs-on: ubuntu-latest
    name: Fetch matrix
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Read matrix file
        id: set-matrix
        run: echo "::set-output name=matrix::$(cat SETTINGS.json | sed 's/ //g')"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  docker_images:
    runs-on: ubuntu-latest
    name: Build and push image
    needs: get-matrix
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.get-matrix.outputs.matrix) }}
        # cuda_version:
        #   - "11.3.0"
        #   - "11.2.1"
        #   - "11.2.0"
        #   - "11.1"
        #   - "11.0"
        #   - "10.2"
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Read VERSION file
      #   id: getversion
      #   run: echo "::set-output name=version::$(cat VERSION)"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/miner-trex-cuda:v${{ matrix.trex_version }}-cuda-${{ matrix.cuda_version }}, ${{ secrets.DOCKERHUB_USERNAME }}/miner-trex-cuda:latest-cuda-${{ matrix.cuda_version }}
          build-args: |
            TREX_VERSION=${{ matrix.trex_version }}
            NVIDIA_CUDA_VERSION=${{ matrix.cuda_version }}

      - name: Get image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  docker_description:
    runs-on: ubuntu-latest
    name: Update dockerhub description
    needs: docker_images
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/miner-trex-cuda
